# Generated by Django 5.2.8 on 2025-11-13 14:55

from django.db import migrations, models


KANBAN_STATUSES = [
    ('novo', 'Novo'),
    ('qualificado', 'Qualificado'),
    ('convertido', 'Convertido'),
    ('perdido', 'Perdido'),
]


def seed_statuses(apps, schema_editor):
    LeadStatus = apps.get_model('leads', 'LeadStatus')
    for order, (key, label) in enumerate(KANBAN_STATUSES):
        LeadStatus.objects.update_or_create(
            key=key,
            defaults={'label': label, 'order': order},
        )


def populate_positions(apps, schema_editor):
    Lead = apps.get_model('leads', 'Lead')
    owner_ids = (
        Lead.objects.all()
        .order_by()
        .values_list('owner_id', flat=True)
        .distinct()
    )
    for owner_id in owner_ids:
        for key, _label in KANBAN_STATUSES:
            qs = (
                Lead.objects.filter(owner_id=owner_id, status=key)
                .order_by('created_at')
            )
            for index, lead in enumerate(qs):
                Lead.objects.filter(pk=lead.pk).update(position=index)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('novo', 'Novo'), ('qualificado', 'Qualificado'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], max_length=20, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=50, verbose_name='Nome da coluna')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Coluna de Kanban',
                'verbose_name_plural': 'Colunas de Kanban',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Posição'),
        ),
        migrations.RunPython(seed_statuses, migrations.RunPython.noop),
        migrations.RunPython(populate_positions, migrations.RunPython.noop),
    ]
